import type { Metadata } from "next";
import { Bebas_Neue, Inter } from "next/font/google";
import "./globals.css";
import TickerBar from "@/components/TickerBar";
import Nav from "@/components/Nav";

const bebasNeue = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bebas",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Underdog Scout — FIFA World Cup 2026",
  description:
    "Tracking the underdog and debut nations of FIFA World Cup 2026, with AI match predictions and nation briefs powered by Groq.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bebasNeue.variable} ${inter.variable} antialiased bg-background text-foreground`}>
        <TickerBar />
        <Nav />
        {children}
        <footer className="border-t border-white/10 mt-16 py-8 text-center text-xs text-foreground/40 px-4">
          <p>
            Underdog Scout — built for FIFA World Cup 2026. Squad, fixture, and live score
            data shown is illustrative sample/demo data. AI insights generated by Groq, PDF
            reports by IBM Docling.
          </p>
        </footer>
      </body>
    </html>
  );
}
