#!/usr/bin/env python3
"""Builds a structured scout report with IBM Docling, then renders it to a PDF
with reportlab (Docling itself has no PDF export — only HTML/Markdown/JSON/text).
Reads prediction JSON on stdin, writes PDF bytes to stdout.
"""
import io
import json
import sys

from docling_core.types.doc.document import DoclingDocument
from docling_core.types.doc.labels import DocItemLabel
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer


def build_prediction_document(data: dict) -> DoclingDocument:
    team_a = data.get("teamA", "Team A")
    team_b = data.get("teamB", "Team B")
    home_score = data.get("homeScore", 0)
    away_score = data.get("awayScore", 0)
    win_a = data.get("winProbabilityA", 0)
    draw = data.get("drawProbability", 0)
    win_b = data.get("winProbabilityB", 0)
    narrative = data.get("narrative", "")

    doc = DoclingDocument(name="underdog-scout-prediction-report")
    doc.add_title("Underdog Scout — AI Match Report")
    doc.add_heading(f"{team_a} vs {team_b}", level=1)
    doc.add_text(
        DocItemLabel.TEXT,
        f"Predicted Score: {team_a} {home_score} – {away_score} {team_b}",
    )

    doc.add_heading("Win Probabilities", level=2)
    doc.add_text(DocItemLabel.TEXT, f"{team_a} Win: {win_a}%")
    doc.add_text(DocItemLabel.TEXT, f"Draw: {draw}%")
    doc.add_text(DocItemLabel.TEXT, f"{team_b} Win: {win_b}%")

    doc.add_heading("Match Narrative", level=2)
    doc.add_text(DocItemLabel.TEXT, narrative)

    return doc


def build_nation_document(data: dict) -> DoclingDocument:
    name = data.get("name", "Unknown Nation")
    flag = data.get("flag", "")
    group = data.get("group", "—")
    population = data.get("population", "—")
    fifa_ranking = data.get("fifaRanking")
    road_to_2026 = data.get("roadTo2026", [])
    squad = data.get("squad", [])

    doc = DoclingDocument(name="underdog-scout-nation-report")
    doc.add_title(f"{flag} {name} — Scout Report".strip())
    doc.add_heading("Nation Overview", level=1)
    doc.add_text(DocItemLabel.TEXT, f"Group: {group}")
    doc.add_text(DocItemLabel.TEXT, f"Population: {population}")
    if fifa_ranking is not None:
        doc.add_text(DocItemLabel.TEXT, f"FIFA Ranking: #{fifa_ranking}")

    if road_to_2026:
        doc.add_heading("Road to 2026", level=2)
        for event in road_to_2026:
            year = event.get("year", "")
            description = event.get("description", "")
            doc.add_text(DocItemLabel.TEXT, f"{year} — {description}")

    if squad:
        doc.add_heading("Squad Overview", level=2)
        for player in squad:
            doc.add_text(
                DocItemLabel.TEXT,
                f"{player.get('position', '')} — {player.get('name', '')} "
                f"({player.get('club', '')}, age {player.get('age', '?')}, "
                f"{player.get('caps', '?')} caps)",
            )

    return doc


def render_pdf(doc: DoclingDocument) -> bytes:
    buffer = io.BytesIO()
    pdf = SimpleDocTemplate(
        buffer,
        pagesize=LETTER,
        topMargin=0.9 * inch,
        bottomMargin=0.9 * inch,
        leftMargin=0.9 * inch,
        rightMargin=0.9 * inch,
        title="Underdog Scout Report",
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ScoutTitle",
        parent=styles["Title"],
        textColor=colors.HexColor("#1A3A2A"),
        fontSize=22,
        spaceAfter=4,
        alignment=TA_CENTER,
    )
    heading_style = ParagraphStyle(
        "ScoutHeading",
        parent=styles["Heading2"],
        textColor=colors.HexColor("#9C7A1E"),
        spaceBefore=16,
        spaceAfter=8,
    )
    body_style = ParagraphStyle(
        "ScoutBody",
        parent=styles["BodyText"],
        fontSize=11,
        leading=16,
        spaceAfter=6,
    )

    flowables = []
    for item, _level in doc.iterate_items():
        label = getattr(item, "label", None)
        text = getattr(item, "text", "")
        if not text:
            continue
        if label == DocItemLabel.TITLE:
            flowables.append(Paragraph(text, title_style))
            flowables.append(Spacer(1, 6))
            flowables.append(HRFlowable(width="100%", color=colors.HexColor("#C9A84C")))
            flowables.append(Spacer(1, 6))
        elif label == DocItemLabel.SECTION_HEADER:
            flowables.append(Paragraph(text, heading_style))
        else:
            flowables.append(Paragraph(text, body_style))

    flowables.append(Spacer(1, 28))
    flowables.append(
        Paragraph(
            "Generated by Underdog Scout — document structured with IBM Docling.",
            ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8, textColor=colors.grey),
        )
    )

    pdf.build(flowables)
    return buffer.getvalue()


def main() -> int:
    raw = sys.stdin.read()
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        sys.stderr.write(f"Invalid JSON input: {exc}\n")
        return 1

    try:
        report_type = data.get("reportType", "prediction")
        doc = build_nation_document(data) if report_type == "nation" else build_prediction_document(data)
        pdf_bytes = render_pdf(doc)
    except Exception as exc:  # noqa: BLE001
        sys.stderr.write(f"Report generation failed: {exc}\n")
        return 1

    sys.stdout.buffer.write(pdf_bytes)
    sys.stdout.buffer.flush()
    return 0


if __name__ == "__main__":
    sys.exit(main())
